### ISSUE TITLE
Breaks YOURLS

### ISSUE THREAD

**Issue by MorbidEntree** [suculent/yourls-ios-url-schemes-plugin#2]
After I activated this plugin in YOURLS, it broke the script as I described in issue [#1958](https://github.com/YOURLS/YOURLS/issues/1958) on the YOURLS repository.

**Comment by suculent** [comment]
Thanks, I'll look into it. I haven't updated my YOURLS since 2 years...

**Comment by suculent** [comment]
Sorry for taking so long. I have upgraded YOURLS and had the same issue like you. If you open 'Manage Plugins' and happen to see YOURLS URL Schemes Plugin by Ozh, that's a fault (probably just remains in database).
Just put a fresh install of this plugin into your user/plugins folder, re-activate the plugin and you should be up and running.
